### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by Hector096** [Tchilo/toDoList#6]
You did absolutely fantastic job on this project. But is always room for improvement.  Hang on, you're almost there: 🗡️ 

When you drag and drop the task it replaces the element which is not the requirement it should change the index (for example: when I drag the third element from the list to 7th position then 4th element index changes to 3 and 7th index changes to 6th and 3 element index changes to 7th )

If you still have any questions do let me know vis slack.

**Comment by Tchilo** [comment]
Thanks, @Hector096  I will look into it
